### PR TITLE
add h5md build test

### PR DESCRIPTION
**Pull request by junghans**
I am a bit confused why it fails, any idea?

See: https://travis-ci.org/junghans/csg/jobs/91315710

### CODE REVIEW

**Comment by jkrajniak** [comment]
This is because Ubuntu has libhdf5 in version 1.8.4 compiled with default api version v16.

**Comment by junghans** [comment]
Thanks, it there anything we can do to fix this? Or at least tweak the cmake check to fail?

**Comment by jkrajniak** [comment]
I've added check for API on the CMake level. The only solution that I see is to compile own version of hdf5 during the test.. (https://github.com/MrTheodor/csg/commit/451fbf57398468b208a3e3d064f6732d00caf1fe)

**Comment by junghans** [comment]
https://answers.launchpad.net/ubuntu/+source/hdf5/+question/124428

**Comment by jkrajniak** [comment]
I am not sure about this way, I've just made it compatible with travis but then if one has hdf5 compiled with flag --disable-deprecated-symbols it would break even if we set H5_USE_16_API. Those macros that they provide does not take into account that the functions changed also the list of arguments.

https://travis-ci.org/MrTheodor/csg/jobs/92216842

**Comment by junghans** [comment]
I think we should build our own hdf5 for now. Travis is based on Ubuntu 12.04, but later Ubuntu version the API got changed, so we will be good at some point in the future.

**Pull request merged**
